export const LOREM = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis nisl, cursus at sapien commodo, venenatis sodales lorem. Phasellus sodales dapibus nunc in dignissim. Morbi et risus lorem. Etiam non euismod dolor. Donec eu urna maximus, interdum eros non, ultrices lacus. Morbi porttitor arcu sed eros pharetra eleifend. Ut molestie sagittis leo, hendrerit vestibulum mi placerat eu. Suspendisse potenti.

Nullam nec hendrerit elit. Aliquam eu massa at quam ullamcorper finibus. Nulla at felis sed nulla egestas rutrum. Proin facilisis metus dui. Integer vulputate hendrerit pharetra. Donec a nibh fringilla, sollicitudin ligula sit amet, luctus arcu. Nulla pharetra euismod orci et molestie. Nunc feugiat tellus vel sem sodales efficitur. Duis non volutpat neque, at vulputate ex. Donec rhoncus ullamcorper mi, quis luctus lacus condimentum sit amet. Nunc dapibus sit amet neque ac rutrum. Fusce sodales massa imperdiet feugiat rhoncus.

Cras efficitur ante lacinia lectus tincidunt semper. Nulla iaculis malesuada ante sed malesuada. Curabitur ligula tellus, auctor a augue eget, maximus elementum lectus. Donec vulputate ligula tortor, nec aliquet augue pretium a. Nullam facilisis porta mi id ornare. In sit amet viverra metus, eu euismod augue. Sed eget auctor velit, sit amet volutpat tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam dignissim augue congue sagittis fringilla. Donec laoreet lacus dui, ut aliquet odio vehicula eu. Vivamus pellentesque dolor dictum velit ultrices, et feugiat diam vestibulum. Nulla bibendum maximus condimentum. Suspendisse hendrerit libero est, facilisis vulputate ligula hendrerit in. Fusce vitae tincidunt magna. Morbi eget lacus dictum lorem lacinia semper. Proin iaculis justo dolor, sed vehicula enim bibendum eu.

Donec egestas lacus sit amet diam eleifend imperdiet. Vestibulum sit amet risus mi. Proin erat libero, condimentum non enim vitae, lobortis eleifend lectus. Nullam posuere pellentesque nisl quis pellentesque. Nullam ultrices lorem a finibus vulputate. Integer nunc ante, auctor sit amet elit ac, sodales elementum lacus. Duis felis quam, gravida a mauris mollis, fringilla vulputate lorem. Phasellus varius quam ac lorem facilisis ultrices. Vestibulum pulvinar eu magna et aliquam. Donec finibus erat non convallis mattis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent sed quam id leo vehicula fringilla. Fusce viverra justo at magna maximus, euismod egestas elit vulputate. Vestibulum malesuada nibh sed tellus venenatis euismod. Donec et ex sodales risus imperdiet feugiat imperdiet nec ipsum. Sed venenatis enim eu lorem euismod condimentum.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla id nunc id velit pretium ullamcorper. In volutpat dolor non nisi pretium, non lacinia massa cursus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis mi id justo sodales cursus. Sed eget ante blandit, feugiat magna in, gravida sapien. Nam posuere mattis metus tristique porta. Sed non eros eget eros dictum dignissim eu ultricies dolor. Suspendisse nunc tortor, iaculis sit amet scelerisque id, auctor eu augue.

Praesent vulputate molestie lectus, eu facilisis orci interdum nec. Praesent vitae congue ipsum. Pellentesque odio sem, eleifend nec neque non, sodales aliquam arcu. Suspendisse lorem nunc, semper at risus vitae, facilisis.`;

export const LOREM_ARRAY = LOREM.split(" ");
